# Generated by Django 3.1.3 on 2020-11-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20201103_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
