# Generated by Django 3.1.3 on 2020-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_auto_20201103_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('name', 'family')},
        ),
    ]
